### ISSUE TITLE
ImportError: cannot import name 'deform_conv_cuda'

### ISSUE THREAD

**Issue by LiXiAng9867** [JialeCao001/SipMask#40]
Traceback (most recent call last):
  File "./tools/test_video.py", line 10, in <module>
    from mmdet import datasets
  File "/ytvis/SipMask/SipMask-VIS/tools/../mmdet/datasets/__init__.py", line 2, in <module>
    from .cityscapes import CityscapesDataset
  File "/ytvis/SipMask/SipMask-VIS/tools/../mmdet/datasets/cityscapes.py", line 1, in <module>
    from .coco import CocoDataset
  File "/ytvis/SipMask/SipMask-VIS/tools/../mmdet/datasets/coco.py", line 4, in <module>
    from .custom import CustomDataset
  File "/ytvis/SipMask/SipMask-VIS/tools/../mmdet/datasets/custom.py", line 10, in <module>
    from .extra_aug import ExtraAugmentation
  File "/ytvis/SipMask/SipMask-VIS/tools/../mmdet/datasets/extra_aug.py", line 5, in <module>
    from mmdet.core.evaluation.bbox_overlaps import bbox_overlaps
  File "/ytvis/SipMask/SipMask-VIS/tools/../mmdet/core/__init__.py", line 6, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "/ytvis/SipMask/SipMask-VIS/tools/../mmdet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms, multiclass_nms_idx
  File "/ytvis/SipMask/SipMask-VIS/tools/../mmdet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper
  File "/ytvis/SipMask/SipMask-VIS/tools/../mmdet/ops/__init__.py", line 2, in <module>
    from .dcn import (DeformConv, DeformConvPack, DeformRoIPooling,
  File "/ytvis/SipMask/SipMask-VIS/tools/../mmdet/ops/dcn/__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "/ytvis/SipMask/SipMask-VIS/tools/../mmdet/ops/dcn/deform_conv.py", line 9, in <module>
    from . import deform_conv_cuda
ImportError: cannot import name 'deform_conv_cuda'

I tried to install mmdet using cmd and dockerfile given in SipMask-VIS repo while all come into this error. This error should because the mmdet.ops has been deleted and moved the functions to mmcv.ops. Since you use a customed mmdet file in SipMask-VIS, I cannot use the recently released mmcv. Could you tell me which mmcv you used or update the docker? So that I can install it either. Thank you!

**Comment by JialeCao001** [comment]
@LiXiAng9867 Thanks for intrest. It is mmcv0.2.12.

**Comment by LiXiAng9867** [comment]
Thank you very much!

**Comment by ollefager** [comment]
Did this solve it for you? because I also get a similar error (ImportError: cannot import name 'deform_conv_cuda' from partially initialized module 'mmdet.ops.dcn') and I still get it with mmcv 0.2.12 installed. I also got a new error (ModuleNotFoundError: No module named 'mmcv.runner.dist_utils') first (there's only an utils folder in the site-packages folder, no dist_utils). By changing dist_utils to utils I could bypass this error, however that's when I get the ImportError again.

**Comment by LiXiAng9867** [comment]
To be honest, not. I got stuck here for days. I tried lots of methods while non of them works.

**Comment by ollefager** [comment]
Too bad. Same here. I have no trouble installing and using just mmdetection. But when trying to train the SipMask model from SipMask-VIS I run into this problem.

**Comment by JialeCao001** [comment]
@LiXiAng9867 @ollefager I am not sure that it is working on docker. can you check this issue. https://github.com/JialeCao001/SipMask/issues/12#issuecomment-691835483

**Comment by ollefager** [comment]
So I had missed this issue https://github.com/JialeCao001/SipMask/issues/9. Running the setup of mmdetection in SipMask-VIS instead of in mmdetection seem to have actually gotten rid of the 'deform_conv_cuda' error. However I still get the error, ModuleNotFoundError: No module named 'mmcv.runner.dist_utils', mentioned earlier. Changing mmcv.runner.dist_utils to mmcv.runner.utils seems to fix the issue, but it also feels like I maybe should not change this. This is in th the file 'SipMask-VIS/mmdet/datasets/loader/sampler.py'.

**Comment by JialeCao001** [comment]
@ollefager Do you solve it? In fact, you donot need to install the original mmdetection. Just download our SipMask-VIS, treat it as the mmdetection, cd SipMask-VIS, and install the enviroments similar to the origianl mmdetection.

**Comment by ollefager** [comment]
yes, running the setup in SipMask-VIS works for me! Maybe something should be said about this in the installation instructions. Because now it says to download mmdetection and cd to mmdetection and run the setup

**Comment by JialeCao001** [comment]
@ollefager Thanks for suggestions. We fix it.
